export const GET_INITIAL_STATE = "GET_INITIAL_STATE"
export const FILTER_All_PRODUCTS_BY_PRICE_CATEGORY = "FILTER_All_PRODUCTS_BY_PRICE_CATEGORY"
export const SEARCH = "SEARCH"
export const ADD_TO_CARD = "ADD_TO_CARD"